### ISSUE TITLE
Add RTL to posts with lang:Hebrew tag

### ISSUE THREAD

**Issue by mushon** [whiletrue-industries/Chronomaps#10]

**Comment by mushon** [comment]
Alternatively, use a language detection script

**Comment by akariv** [comment]
Detecting by first letter's language, affects notes + title + hover.

**Comment by mushon** [comment]
Should affect the text in the posts as well:

![Image](https://github.com/whiletrue-industries/Chronomaps/assets/27123/710aa06f-754e-496d-9c99-0f913e99f420)

**Comment by akariv** [comment]
done

**Comment by mushon** [comment]
Great, also please make sure the icons below stay together aligned left


![Image](https://github.com/whiletrue-industries/Chronomaps/assets/27123/6448dc74-a7b9-4f3c-981d-0f43c04557c0)
