### ISSUE TITLE
Add font stack for Hebrew support

### ISSUE THREAD

**Issue by mushon** [whiletrue-industries/Chronomaps#17]
We will use Rag-Sans as the Hebrew font fallback

**Comment by akariv** [comment]
Cool, we need to purchase it though, no?

**Comment by mushon** [comment]
I'm double checking how restrictive (or not) is the license

**Comment by mushon** [comment]
Let's use Assistant instead:
https://fonts.google.com/specimen/Assistant?stroke=Sans+Serif&subset=hebrew&noto.script=Hebr

**Comment by akariv** [comment]
done
