### ISSUE TITLE
Develop Directory Front-End

### ISSUE THREAD

**Issue by mushon** [whiletrue-industries/Chronomaps#2]

**Comment by akariv** [comment]
First draft, pending design fine tuning:

https://whiletrue-industries.github.io/Chronomaps/

**Comment by mushon** [comment]
Very exciting.
Do you want me to give you design feedback now or after you implement the mobile version?

**Comment by akariv** [comment]
I haven't worked on the mobile version at all, so feel free to give fixes
on the desktop version.
Note that the image you have uploaded for the title (the red text) has the
wrong size (unnecessarily padded in the bottom), so please fix that before
going over the design.

**Comment by mushon** [comment]
Visual QA here: https://www.figma.com/file/ZxU6ydf7dJ5GmboIpxe2E5/Atlas_Med_Liq?type=design&node-id=5359-55438&mode=design&t=wpj7q3LuJ3VzHfyR-11

**Comment by akariv** [comment]
I went over all comments in Figma.
