### ISSUE TITLE
Add the draft media types (sticky note)

### ISSUE THREAD

**Issue by mushon** [whiletrue-industries/Chronomaps#21]
Any new contribution will start with a sticky note, even before choosing format:
![Image](https://github.com/whiletrue-industries/Chronomaps/assets/27123/24536685-0297-453d-b442-3fb952ffdb6f)

The text-size in the sticky will adjust to fit the available space using [fluid type](https://www.madebymike.com.au/writing/fluid-type-calc-examples/). The format can be selected in this screen or later in the details screen (or stay like this as a sticky note):
![Image](https://github.com/whiletrue-industries/Chronomaps/assets/27123/423a6750-1d72-404a-8fa2-96b021266eb1)

**Comment by mushon** [comment]
start with simple post it (maybe + color)

**Comment by akariv** [comment]
No, notes can be submitted (e.g. https://manage.chronomaps.net/database/37/table/143/269/row/26).

The form was buggy, it declared fields to be required while they were not visible due to conditions, so the submit button did not allow submitting the form.
