### ISSUE TITLE
Implement default map view

### ISSUE THREAD

**Issue by mushon** [whiletrue-industries/Chronomaps#28]
The value Default_Map_View is optional in the settings table.
if empty, the view should be zoomed out to furthest extent of the points. 
For input we would use the same format as here: https://labs.mapbox.com/location-helper/#4.07/40.99/14.23/0/1

**Comment by mushon** [comment]
this one is important

**Comment by akariv** [comment]
Also need to make sure this is in the template.

**Comment by akariv** [comment]
done
