### ISSUE TITLE
Choose a domain

### ISSUE THREAD

**Issue by mushon** [whiletrue-industries/Chronomaps#29]

**Comment by mushon** [comment]
Some available options:
- [ ] chrono-maps.com
- [ ] crnmps.com
- [ ] crnmaps.com
- [ ] chronomap.ing
- [ ] crnmp.ing
- [ ] chronomaps.art
- [ ] chronomaps.world
- [ ] chronomaps.xyz
- [ ] chronomaps.wtf
- [ ] chronomaps.social
- [ ] chronomaps.fun
- [ ] chronomaps.place
- [ ] chronomaps.tours

**Comment by akariv** [comment]
chosen domain is chronomaps.net

**Comment by akariv** [comment]
baserow is now up in manage.chronomaps.net
