### ISSUE TITLE
Two map styles have different projections

### ISSUE THREAD

**Issue by akariv** [whiletrue-industries/Chronomaps#33]
One of them is 2d, and the other is 3d. It causes them to lose sync when zoomed out (one remains planar while the other shows the globe).

**Comment by mushon** [comment]
I tried updating the background map to be in 3D too, but it doesn't seem to take effect, the keys are:
mapbox://styles/atlasmedliq/cl59k9bun000y14rzt3yy5ljt
mapbox://styles/atlasmedliq/clr4tn7gd01fq01qr4hvzalwk

It's there:
<img width="731" alt="image" src="https://github.com/whiletrue-industries/Chronomaps/assets/27123/718f6fcb-eb3a-4e76-b1ff-93778df9166f">

It should look like this:
https://api.mapbox.com/styles/v1/atlasmedliq/clr4tn7gd01fq01qr4hvzalwk.html?title=view&access_token=pk.eyJ1IjoiYXRsYXNtZWRsaXEiLCJhIjoiY2tpbXgzNW5qMHhhcjJ5cGtydHpkNnJqYyJ9.vfietFuvTA8S1vaGlm3CUQ&zoomwheel=true&fresh=true#2.02/60.68/28

But [it doesn't](https://whiletrue-industries.github.io/Chronomaps/sea-change#1581631199999/1/-1735698040000/0//32)

Any ideas?

**Comment by akariv** [comment]
The current styles in use are:
base: mapbox://styles/atlasmedliq/ckiodibg82x1k17tcof8e9pmd
detail: mapbox://styles/atlasmedliq/cl59k9bun000y14rzt3yy5ljt

**Comment by akariv** [comment]
I changed it to use the styles from settings.

**Comment by mushon** [comment]
I'm trying to change default styles unsuccessfully...
mapbox://styles/atlasmedliq/clrg7xc5c00gp01qnhxv55azw ([doesn't seem to load](https://whiletrue-industries.github.io/Chronomaps/bttf#1703109599999/0.9999814498198968/441756000000/1//24))

**Comment by mushon** [comment]
fixed
